### ISSUE TITLE
Support for Virtual Chassis

### ISSUE THREAD

**Issue by Olen** [exaring/openconfig-streaming-telemetry-exporter#14]
I don't have enough experience with the telemetry interface (or Go) to verify whether this is a problem with this component or the Junos itself, so bear over with me if this is a Junos issue.
I am trying to use this tool to monitor a VC with 2 x QFX512, running 19.3R2-S4.
One thing is that the ae-interfaces are missing, but I think that is a limitation in Junos.

However I do not see any counters of the interfaces on the secondary node at all.
Querying prometheus for `interfaces_interface_state_counters_out_octets` gives me numbers for all the xe-0/* and et-0/* interfaces but no xe-1/* or et-1/* are found.

I do see both xe-0 and xe-1 in e.g. `interfaces_interface_state_enabled` so it seems to only be the counters that are missing.

The config I have set up is directly from your example config.

**Comment by lgerhold** [comment]
Hi Olen, 

sounds like an issue of JunOS. Unfortunately I have no QFX in a VC here for testing. 

Can you send me an `show ephemeral-configuration instance junos-analytics`?

-Lukas

**Comment by Olen** [comment]
I guess there are no big secrets here, so I'll just add it to the case:
```
services {
    analytics {
        export-profile export_1000 {
            transport grpc;
        }
        export-profile export_1001 {
            transport grpc;
        }
        export-profile export_1002 {
            transport grpc;
        }
        export-profile export_1003 {
            transport grpc;
        }
        export-profile export_1004 {
            transport grpc;
        }
        sensor sensor_1000 {
            export-name export_1000;
            resource "/junos/events/event[id='CHASSISD_SNMP_TRAP7']/";
            subscription-id 1000;
            reporting-rate 0;
            life-time long-lived;
        }
        sensor sensor_1001 {
            export-name export_1001;
            resource /junos/system/cmerror/configuration/;
            subscription-id 1001;
            reporting-rate 6;
            life-time long-lived;
        }
        sensor sensor_1002 {
            export-name export_1002;
            resource /junos/system/cmerror/counters/;
            subscription-id 1002;
            reporting-rate 6;
            life-time long-lived;
        }
        sensor sensor_1003 {
            export-name export_1003;
            resource /components/;
            subscription-id 1003;
            reporting-rate 6;
            life-time long-lived;
        }
        sensor sensor_1004 {
            export-name export_1004;
            resource /interfaces/;
            subscription-id 1004;
            reporting-rate 2;
            life-time long-lived;
        }
    }
}                                     
```

But as I said, I can see both xe-0 and xe-1 interfaces in e.g. state_enabled and state_ifindex. Just not in state_counters_*

**Comment by lgerhold** [comment]
Hi, 

the subscription is fine, so it seems to be an issue of junos. for annother system (acx5448) i have the same symptomes (all counters works, except interface counter). if you have jtac support, give it a try :)

**Comment by lgerhold** [comment]
though you are hitting PR1566528 (The PFE telemetry data might not be streamed out in QFX-VC)

solved in: 



Release | junos
20.3R3 | x
20.4R2 | x
21.1R2 | x
21.2R1 | x

**Comment by Olen** [comment]
Thanks.  I'll contact JTAC.

Althought the headline of the mentioned PR might look relevant, the text in the actual PR seems to be about some log messages regarding agentd on the linecards.  I have no such log messages here, so it seems to be related to something else.

**Comment by Olen** [comment]
Just before I close this case.  Is it "you" or Junos that "resolves" /interfaces to the internal IDs?

I can see in the logs that there is a subscription coming in:

May 27 07:15:58  #431# ConsolidatorSystemHandlePtr created with the id = 1004for request string: Openconfig:long_lived:0:path: "/interfaces/" max_silent_interval: 20000 sample_frequency: 2000
May 27 07:15:58  #432# Subscription client-1-NA_periodic_subscriber MQTT subscribe path: /1004/1/0
May 27 07:15:58  #433# Subscription client-1-NA_periodic_subscriber MQTT subscribe path: /1004/1/1/#

So the "/interfaces" seems to include two paths: /1004/1/0 and /1004/1/1/#

But when I look at `show agent sensors` it seems to be more paths thtat might be interesting:

I guess these are the two we get:

```
Sensor Information : 
           
    Name                                    : sensor_1004           
    Resource                                : /interfaces/          
    Version                                 : 1.0                  
    Sensor-id                               : 539528119             
    Subscription-ID                         : 1004                 
    Parent-Sensor-Name                      : Not applicable       
    Component(s)                            : PFE,PFE,PFE,dcd,mib2d,xmlproxyd 

    Profile Information : 
           
        Name                                : export_1004           
        Reporting-interval                  : 2                     
        Payload-size                        : 5000                  
        Format                              : GPB                   

Sensor Information : 
           
    Name                                    : sensor_1004_1_1       
    Resource                                : /junos/system/linecard/interface/logical/usage/ 
    Version                                 : 1.1                  
    Sensor-id                               : 3143454041            
    Subscription-ID                         : 1004                 
    Parent-Sensor-Name                      : sensor_1004          
    Component(s)                            : PFE                   

    Profile Information : 
           
        Name                                : export_1004           
        Reporting-interval                  : 2                     
        Payload-size                        : 5000                  
        Format                              : GPB                   
```
But then there is also this one:
```
Sensor Information : 
           
    Name                                    : sensor_1004_1_3       
    Resource                                : /junos/system/linecard/interface/traffic/ 
    Version                                 : 1.0                  
    Sensor-id                               : 3143454043            
    Subscription-ID                         : 1004                 
    Parent-Sensor-Name                      : sensor_1004          
    Component(s)                            : PFE                   

    Profile Information : 
           
        Name                                : export_1004           
        Reporting-interval                  : 2                     
        Payload-size                        : 5000                  
        Format                              : GPB                   

```

which seems like it might be what I am missing?

(This is the first time I work with the telemetry stuff, so it is currently lot's of black magic going on here for me)
